




# ====================================================================================
# General Parameters
# ====================================================================================

device: "cuda"
num_datasets: 10
noise_std: 0.1
dh: 10

# ====================================================================================
# Parameters for Classical Models
# ====================================================================================

lr_classical: 0.001
dataset_size_classical: 1000
weight_decay_classical: 0.00001

# ====================================================================================
# Parameters for In-Context Models
# ====================================================================================

lr_in_context: 0.001
dataset_size_in_context: 100
dataset_amount: 10000
weight_decay_in_context: 0.00001