




# ====================================================================================
# General Parameters
# ====================================================================================

wandb_enabled: True
wandb_project_name: "Model-Misspecification"
wandb_exp_name: "Some Experiments"

device: "cuda"
num_datasets: 10
noise_std: 0.05
dh: 10

# ====================================================================================
# Parameters for Classical Models
# ====================================================================================

num_iters_classical: 10000
lr_classical: 0.001
dataset_size_classical: 50
weight_decay_classical: 0.00001

# ====================================================================================
# Parameters for In-Context Models
# ====================================================================================

num_iters_in_context: 10000
lr_in_context: 0.001
dataset_size_in_context: 50
dataset_amount: 10000
weight_decay_in_context: 0.00001
batch_size_in_context: 100