




# ====================================================================================
# General Parameters
# ====================================================================================

num_datasets: 10
noise_std: 0.1

# ====================================================================================
# Parameters for Classical Models
# ====================================================================================

lr_classical: 0.001
dataset_size_classical: 1000